const GOOD_RESPONSE = 200;
const REDIRECT = 301;
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const INTERNAL_SERVER_ERROR = 500;

export { GOOD_RESPONSE };

export { REDIRECT };

export { BAD_REQUEST, UNAUTHORIZED, FORBIDDEN, NOT_FOUND };

export { INTERNAL_SERVER_ERROR };
